[build-system]
requires = [
    "hatchling==1.28.0",
]
build-backend = "hatchling.build"

[project]
name = "pyiron_nodes"
description = "pyiron nodes"
authors = [
    { name = "Jörg Neugebauer", email = "neugebauer@mpi-susmat.de" },
]
copyright = "© 2025 Jörg Neugebauer"
requires-python = ">3.9"
dependencies = [
    "numpy",
    "ase",
    "matgl",
    "pandas",
    "matplotlib",
    "structuretoolkit",
    "tqdm",
    "tensorpotential",
    "pyiron_atomistics",
    "pyiron_snippets",
    "pymatgen",
    "pyiron_lammps",
    "calphy",
    "atomistics",
    "scipy",
]
version = "0.0.1"

[tool.hatch.build]
include = [
    "pyiron_nodes"
]

[tool.hatch.build.targets.sdist]
include = [
    "pyiron_nodes"
]

[tool.hatch.build.targets.wheel]
packages = [
    "pyiron_nodes"
]
