channels:
- conda-forge
dependencies:
- python >=3.11,<3.14
- hatchling =1.27.0
- hatch-vcs =0.5.0
- hatch-jupyter-builder >=0.5.0
- anywidget =0.9.18
- cloudpickle =3.1.2
- ipykernel =6.31.0
- ipytree =0.2.2
- ipywidgets =8.1.6
- jupyterlab =4.4.1
- numpy =1.26.4
- sqlalchemy =2.0.38
- traitlets =5.14.3
- ase =3.28.0
- assyst =0.13.0
- calphy =1.7.2
- grace-tensorpotential =0.5.5
- iprpy-data =2023.07.25
- lammps =2024.08.29=*openmpi*
- landau =1.7.0
- matgl =2.0.6
- matplotlib =3.10.9
- nglview =3.1.4
- pandas =2.2.3
- phonopy =2.47.1
- pint =0.25.2
- pyiron-data =0.0.30
- lammpsparser =0.0.3
- pylammpsmpi =0.3.12
- python-ace =0.3.1
- python-ternary =1.0.8
- pyxtal =1.1.2
- scikit-image =0.25.2
- scikit-learn =1.6.1
- scipy =1.15.2
- seaborn =0.13.2
- structuretoolkit = 0.0.42
- pysqa =0.4.1
- h5py =3.15.1
- executorlib =1.9.2
- chromadb =1.5.5
- openai =2.29.0
- pytest =7.4.2