channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.13
  - ase =3.23.0
  - lammps =2024.02.07
  - matgl =1.1.2
  - matplotlib =3.9.1
  - numpy =1.26.4
  - pandas =2.2.2
  - phonopy =2.26.6
  - pyiron_atomistics =0.6.9
  - pyiron_base =0.9.10
  - pyiron_contrib =0.1.17
  - pyiron-data =0.0.30
  - pymatgen =2024.7.18
  - scipy =1.14.0
  - sqlalchemy =2.0.31
  - structuretoolkit =0.0.27
  
