channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- python >=3.11,<3.13
- ase =3.23.0
- atomistics =0.1.32
- lammps =2024.06.27
- matgl =1.1.3
- matplotlib =3.9.2
- nglview =3.1.2
- numpy =1.26.4
- pandas =2.2.2
- phonopy =2.26.6
- pyiron_atomistics =0.6.16
- pyiron_base =0.9.12
- pyiron_contrib =0.1.18
- pyiron-data =0.0.30
- pyiron_workflow =0.10.2
- pymatgen =2024.8.9
- scipy =1.14.1
- sqlalchemy =2.0.32
- structuretoolkit =0.0.28
