# This runs cron jobs daily

name: Daily

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  codeql:
    uses: pyiron/actions/.github/workflows/tests-and-coverage.yml@actions-3.2.1
    secrets: inherit
    with:
      python-version: '3.11'  # Instead of default 3.12