# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-Pull

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/push-pull.yml@actions-3.2.1
    secrets: inherit
    with:
      python-version: '3.11'  # Instead of default 3.12
      python-version-alt1: 'exclude'  # Is just 3.11
      python-version-alt3: 'exclude'  # No python 3.9
      runner-alt1: 'exclude'  # No windows tests due to Lammps
